modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="https://github.com/kawaiicakes/VS-Create-Armor-Forge/issues"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
displayURL="https://curseforge.com/minecraft/mc-mods/vs2-cbc-armor-blocks"
logoFile="icon.png"
authors="${mod_authors}"
description='''${mod_description}'''

[[dependencies."${mod_id}"]]
    modId="forge"
    mandatory=true
    versionRange="${forge_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies."${mod_id}"]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
